backend:
  name: github
  repo: Goblinlordx/netlifire
  branch: master
  base_url: https://us-central1-netlifire.cloudfunctions.net
  auth_endpoint: /oauth/github/auth

media_folder: "data/media"
public_folder: "data/media"

site_url: https://netlifire.web.app

collections:
  - name: "home"
    label: "Home"
    description: "Home page"
    file: "src/pages/index.mdx"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "posts"
    label: "Posts"
    description: "Posts"
    folder: "data/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
